#Welcome greeting banner for user
print("======================")
print("Welcome to Aristotle's Auto!")
print("Est. 2022")
print("Car customization Form")
print("======================")      
print()
print()
#Get model of car from the user
print("What model of car are you ordering?")
print("  a. Light Cruise")
print("  b. Night Ride")
print("  c. Figure Eight")
print("  d. Titan")
userModel = input("Please enter 'a' - 'd': ")
print()
#Get choice of car fuel preference from the user
print("What fuel type are you selecting? ")
print(" a. Electric Vehicle ")
print(" b. Hybrid Vehicle (electric/gas) ")
print(" c. Gas Vehicle (unleaded fuel)" )
userFuel = input("Please enter 'a' - 'c' ")
print()
#Get color of car from the user
print(" < Exterior >")
print("What color do you like for your car?")
userColor = input("Please enter any color for your car: ")
print()
#Get sunroof answer from the user
print("Would you like to add a sunroof for your car? ")
userSunroof = input("Please enter 'yes' or 'no': ")
print()
print(" < Interior >")
#Get option of of leather seats from the user
print("Would you like to have leather seats? ")
userLeather = input("Please enter 'yes' or ' no': ")
print()
#Get add backseat lcd display monitors from the user
print("Would you like to add backseat LCD Display Monitors? ")
userLcd = input("Please enter 'yes' or 'no': ")
print()
#Get first name of the user
print("< User's First Name > ")
userFirst = input("Please enter your first name: ")
print()
#Get email address of the user
print("< User Email Address > ")
userEmail = input("Please enter your email address: ")
print()
print()
#Summary of user selections
print("===================")
print("--=== Summary ===-- ")
print()
print(f"Model option: {userModel} ")
print(f"Fuel preference: {userFuel} ")
print(f"Color preference: {userColor} ")
print(f"Sunroof option: {userSunroof} ")
print(f"Leather Seats option: {userLeather} ")
print(f"Backseat LCD Display Monitors option: {userLcd} ")
print()
#End greeting
print(f"Thank you, {userFirst}, for visiting Aristotle's Auto! ")
print(f"A copy of your summary will be sent to: {userEmail} ")
print()
